[package]
name = "roLos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
strum_macros = "0.25.1"
termcolor = "1.2.0"
